# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gpx2png"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aleksander Kwiatkowski"]
  s.date = "2013-12-23"
  s.description = "Convert routes to image map files using Openstreetmap tileset."
  s.email = "bobikx@poczta.fm"
  s.executables = ["gpx2png"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/gpx2png",
    "lib/gpx2png.rb",
    "lib/gpx2png/assets/sample_marker.rb",
    "lib/gpx2png/base.rb",
    "lib/gpx2png/calculations/base_class_methods.rb",
    "lib/gpx2png/calculations/base_instance_methods.rb",
    "lib/gpx2png/calculations/osm_class_methods.rb",
    "lib/gpx2png/calculations/osm_instance_methods.rb",
    "lib/gpx2png/landscape.rb",
    "lib/gpx2png/layer.rb",
    "lib/gpx2png/opencycle.rb",
    "lib/gpx2png/osm.rb",
    "lib/gpx2png/osm_base.rb",
    "lib/gpx2png/outdoors.rb",
    "lib/gpx2png/renderers/chunky_png_renderer.rb",
    "lib/gpx2png/renderers/rmagick_renderer.rb",
    "lib/gpx2png/transport.rb",
    "lib/gpx2png/ump.rb"
  ]
  s.homepage = "http://github.com/akwiatkowski/gpx2png"
  s.licenses = ["LGPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Convert routes to image map files using Openstreetmap tileset"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mini_exiftool>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_runtime_dependency(%q<gpx_utils>, [">= 0"])
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<mini_exiftool>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<gpx_utils>, [">= 0"])
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mini_exiftool>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<gpx_utils>, [">= 0"])
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

